# Generated by Django 3.2.3 on 2021-07-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0005_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contactus',
        ),
        migrations.DeleteModel(
            name='text',
        ),
    ]
