# Generated by Django 3.2.3 on 2021-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0006_auto_20210722_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
