# Generated by Django 3.2.3 on 2021-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0007_alter_contactus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
    ]
