# Generated by Django 3.2.3 on 2021-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0009_auto_20210722_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
