# Generated by Django 3.2.3 on 2021-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0010_auto_20210723_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='none', upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
