# Generated by Django 3.2.3 on 2021-07-23 08:55

from django.db import migrations, models
import needyamin.models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=needyamin.models.user_directory_path),
        ),
    ]
