# Generated by Django 3.2.3 on 2021-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
