# Generated by Django 3.2.3 on 2021-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0017_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('keywords', models.CharField(max_length=2000)),
                ('privacy', models.CharField(max_length=5000)),
                ('aboutus', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='privacy',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
