# Generated by Django 3.2.3 on 2021-08-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0018_auto_20210801_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
