# Generated by Django 3.2.3 on 2021-08-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0019_email_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='script_add',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='aboutus',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
