# Generated by Django 3.2.3 on 2021-08-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needyamin', '0020_auto_20210805_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favourite_icon',
            field=models.ImageField(blank=True, null=True, upload_to='favourite_icon/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='aboutus',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
